### PR TITLE
consolidate analyze and corrected capacitance term

### PR DESCRIPTION
**Pull request by kongjy**
previously analyze was split into two cases: one where the number of total points was an integer multiple of the number of points per CPD and one that was not. this is removed and the extra points (are assumed to be at the end and) are simply left out out of the analysis 

capacitance term previously was set to offset in quadratic fit; changed to a term.

### CODE REVIEW

**Comment by rajgiriUW** [comment]
What is the benefit of leaving the data off at the end? Just so you have an exact number of cycles or readibility? 

Good catch on the capacitance thing!

**Comment by kongjy** [comment]
Unless I'm missing something, it seems like splitting it up into two cases where remainder = 0 and remainder is non-zero is not necessary. So, readability. Also, the extra points aren't lopped off and are still part of self.signal_array, just not processed in the analyze method.

**Comment by rajgiriUW** [comment]
There aren't two cases. It runs the first loop (the for loop). Then, if there are any point that aren't accounted for (remainder), it processes those.

But, this also only ever changes the last point on the CPD trace, so it probably doesn't matter

**Comment by kongjy** [comment]
My bad on this one; I'll add it back next PR for completeness.

**Pull request merged**
